Homework 8 completed
akulebyakin/AndreiKulebiakin pull request #9
Opened 2020-09-14 19:21 UTC by akulebyakin

JDI

2020-09-15 07:36 UTC, troe88 requested changes

2020-09-15 07:36 UTC, troe88 commented on src/test/java/hw8/testdata/JdiSiteDataProvider.java
> +    private ArrayList<MetalsAndColors> getMetalsAndColorsDataFromJson(String filepath)
Take a look at the Gson library and TypeToken specifically

2020-09-15 07:36 UTC, troe88 commented on src/test/java/hw8/testdata/FormData.java
> +public class FormData {
What kind of FormData is this ? What is the reason of two similar classes (MetalsAndColors ) ?

2020-09-15 07:36 UTC, troe88 commented on src/test/java/hw8/tests/JdiSiteTest.java
> +public class JdiSiteTest implements TestsInit {
Typical example of overdesign. Take a look at the task, you should create only ONE test with ONE dataprovider. It is not make sense at all to use DP everywhere.

2020-09-15 07:36 UTC, troe88 commented on src/test/java/hw8/tests/JdiSiteTest.java
> +        homePage.userName.assertThat().displayed();
You can use JDI assertions like ement.is().text("expected text")

2020-09-15 07:36 UTC, troe88 commented on src/test/java/hw8/tests/JdiSiteTest.java
> +        MetalsAndColorsPage.metalsAndColorsForm.fill(formData);
It will be better to create fomr::submit(entity) method instead of 2 methods (fill and submit)

2020-09-15 12:19 UTC, akulebyakin commented on src/test/java/hw8/testdata/FormData.java
> +public class FormData {
Oops... I don't know how it got to the final cut.
Fixed.

2020-09-15 12:27 UTC, akulebyakin commented on src/test/java/hw8/tests/JdiSiteTest.java
> +        MetalsAndColorsPage.metalsAndColorsForm.fill(formData);
Agree. Done!

2020-09-15 12:29 UTC, akulebyakin commented on src/test/java/hw8/tests/JdiSiteTest.java
> +        homePage.userName.assertThat().displayed();
Done

2020-09-15 16:45 UTC, akulebyakin commented on src/test/java/hw8/tests/JdiSiteTest.java
> +public class JdiSiteTest implements TestsInit {
Changed it to just one test

2020-09-15 19:03 UTC, akulebyakin commented on src/test/java/hw8/testdata/JdiSiteDataProvider.java
> +    private ArrayList<MetalsAndColors> getMetalsAndColorsDataFromJson(String filepath)
Done

2020-09-17 08:00 UTC, troe88 approved these changes

2020-09-17 08:01 UTC, merged